require('packer-plugins')

require('core/options')
require('core/colors')
require('core/autocmds')
require('core/keymaps')
require('core/statusline')
require('core/barbar')

require('plugins/alpha-nvim')
require('plugins/indent-blankline')
require('plugins/lsp-installer')
require('plugins/nvim-lspconfig')
require('plugins/lsp-saga')
require('plugins/nvim-cmp')
require('plugins/nvim-tree')
require('plugins/nvim-treesitter')
require('plugins/telescope')
