#!/bin/bash
# Format QML files in the QuickShell project: the given files, or all of them

QMLFORMAT="/usr/lib/qt6/bin/qmlformat"

if (($#)); then
  "$QMLFORMAT" -i "$@"
else
  find . -name "*.qml" -type f -exec "$QMLFORMAT" -i {} +
fi
