[tools]
"aqua:LuaLS/lua-language-server" = "latest"
biome = "latest"
bun = "latest"
gh = "latest"
go = "latest"
java = "26"
node = "lts"
"npm:@tailwindcss/language-server" = "latest"
opencode = "latest"
taplo = "latest"
typst = "latest"
usage = "latest"
