[tools]
"aqua:LuaLS/lua-language-server" = "latest"
biome = "latest"
bun = "latest"
go = "latest"
just = "latest"
node = "lts"
"npm:@astrojs/language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:typescript" = "latest"
"npm:prettier" = "latest"
"npm:vscode-langservers-extracted" = "latest"
stylua = "latest"
taplo = "latest"
usage = "latest"

[settings]
auto_update = true
