unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix

# General
set -g default-terminal "${TERM}"
set -ag terminal-features ",*:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g pane-border-indicators both
set -g set-clipboard on

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Load custom hooks
source-file ~/.config/tmux/hooks.conf

set -g status-position bottom
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""
set -gw automatic-rename on
set -gw automatic-rename-format '#{b:pane_current_path}'

set -g status-style "bg=default,fg=default"
set -g status-left "#[fg=#BAA0E8,bold] #S "
set -g status-right "#[fg=#BAA0E8]#{?pane_in_mode,COPY ,}#{?client_prefix,CMD ,}#{?window_zoomed_flag,ZOOM ,}#[fg=#6D5978]#h "
set -g window-status-format "#[fg=#6D5978] #I:#W "
set -g window-status-current-format "#[fg=#BAA0E8,bold] #I:#W "
set -g pane-border-style "fg=#6D5978"
set -g pane-active-border-style "fg=#BAA0E8"
set -g message-style "bg=default,fg=#BAA0E8"
set -g message-command-style "bg=default,fg=#BAA0E8"
set -g mode-style "bg=#BAA0E8,fg=#1E1F29"
setw -g clock-mode-colour "#BAA0E8"

unbind %
unbind '"'
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded Config!"
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind-key h select-pane -L
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D
bind C-n previous-window
bind C-p next-window

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "omerxx/tmux-sessionx"

set -g @sessionx-bind 'o'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-weight '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-preview-enabled 'false'
set -g @sessionx-bind-select-up 'ctrl-p'
set -g @sessionx-bind-select-down 'ctrl-n'

set -g @continuum-restore 'off'
set -g @resurrect-strategy-nvim 'session'

run '~/.tmux/plugins/tpm/tpm'
