#!/bin/bash

set -euo pipefail

EXTENSIONS_DIR="$HOME/.local/share/nautilus-python/extensions"

mkdir -p "$EXTENSIONS_DIR"
cp "$DOTFILES_DIR/default/nautilus-python/extensions"/*.py "$EXTENSIONS_DIR/"

# vim: ft=sh
