windowrule {
  name = steam
  match:class = steam

  float = on
  center = on
  tag = -default-opacity
  opacity = 1 1
  idle_inhibit = fullscreen
}

windowrule {
  name = steam-main
  match:class = steam
  match:title = Steam

  size = 1300 820
}

windowrule {
  name = steam-friends
  match:class = steam
  match:title = Friends List

  size = 460 800
}

windowrule {
  name = steam-game
  match:class = steam_app_.*

  tag = -default-opacity
  tag = +floating-window
  opacity = 1 1
  keep_aspect_ratio = on
  idle_inhibit = fullscreen
}
