windowrule {
    name = steam
    match:class = steam

    float = on
    center = on
    tag = -default-opacity
    opacity = 1 1
    idle_inhibit = fullscreen
}

windowrule {
    name = steam-main
    match:class = steam
    match:title = Steam

    size = 1100 700
}

windowrule {
    name = steam-friends
    match:class = steam
    match:title = Friends List

    size = 460 800
}
