hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm-app -- qs")
    hl.exec_cmd("uwsm-app -- elephant")
    hl.exec_cmd("uwsm-app -- walker --gapplication-service")
    hl.exec_cmd("uwsm-app -- vesktop", { workspace = "special:discord silent" })
end)
