require("colors")
require("monitors")
require("input")
require("looknfeel")
require("events")
require("windows")
require("bindings")
require("workspaces")

require("apps.browsers")
require("apps.localsend")
require("apps.pip")
require("apps.steam")
require("apps.discord")
