# envs are loaded in uwsm

source = ./colors.conf
source = ./autostart.conf
source = ./bindings.conf
source = ./input.conf
source = ./looknfeel.conf
source = ./monitors.conf
source = ./windows.conf

source = ./apps/browsers.conf
source = ./apps/localsend.conf
source = ./apps/pip.conf
source = ./apps/steam.conf
